<?php
/**
 * Capability catalogue and role map.
 *
 * @package SIQA\AulaVirtual
 */

declare( strict_types = 1 );

namespace SIQA\AulaVirtual\Permissions;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Declares every capability used by the plugin and how roles map to them.
 *
 * Course capabilities are delegated to the custom post type through
 * `map_meta_cap`, so ownership checks (an instructor editing only their own
 * courses) are handled by WordPress core. Everything that lives in custom
 * tables gets an explicit `av_*` capability.
 */
final class Capabilities {

	/**
	 * Singular capability type of the course post type.
	 */
	public const COURSE_SINGULAR = 'av_course';

	/**
	 * Plural capability type of the course post type.
	 */
	public const COURSE_PLURAL = 'av_courses';

	public const MANAGE_LMS         = 'av_manage_lms';
	public const MANAGE_EDITIONS    = 'av_manage_editions';
	public const MANAGE_CURRICULUM  = 'av_manage_curriculum';
	public const MANAGE_MATERIALS   = 'av_manage_materials';
	public const MANAGE_LIVE_CLASS  = 'av_manage_live_classes';
	public const VIEW_STUDENTS      = 'av_view_students';
	public const ENROLL_STUDENTS    = 'av_enroll_students';
	public const IMPORT_STUDENTS    = 'av_import_students';
	public const APPROVE_REQUESTS   = 'av_approve_requests';
	public const MANAGE_ANNOUNCE    = 'av_manage_announcements';
	public const VIEW_REPORTS       = 'av_view_reports';
	public const ISSUE_CERTIFICATES = 'av_issue_certificates';
	public const MANAGE_COMMERCE    = 'av_manage_commerce';
	public const MANAGE_PRICES      = 'av_manage_prices';
	public const ACCESS_CAMPUS      = 'av_access_campus';

	/**
	 * Capabilities generated by the course post type.
	 *
	 * @return array<string, string>
	 */
	public static function course_capabilities(): array {
		$singular = self::COURSE_SINGULAR;
		$plural   = self::COURSE_PLURAL;

		return array(
			'edit_post'              => "edit_{$singular}",
			'read_post'              => "read_{$singular}",
			'delete_post'            => "delete_{$singular}",
			'edit_posts'             => "edit_{$plural}",
			'edit_others_posts'      => "edit_others_{$plural}",
			'publish_posts'          => "publish_{$plural}",
			'read_private_posts'     => "read_private_{$plural}",
			'delete_posts'           => "delete_{$plural}",
			'delete_private_posts'   => "delete_private_{$plural}",
			'delete_published_posts' => "delete_published_{$plural}",
			'delete_others_posts'    => "delete_others_{$plural}",
			'edit_private_posts'     => "edit_private_{$plural}",
			'edit_published_posts'   => "edit_published_{$plural}",
			'create_posts'           => "edit_{$plural}",
		);
	}

	/**
	 * Capabilities specific to the modules stored in custom tables.
	 *
	 * @return array<int, string>
	 */
	public static function plugin_capabilities(): array {
		return array(
			self::MANAGE_LMS,
			self::MANAGE_EDITIONS,
			self::MANAGE_CURRICULUM,
			self::MANAGE_MATERIALS,
			self::MANAGE_LIVE_CLASS,
			self::VIEW_STUDENTS,
			self::ENROLL_STUDENTS,
			self::IMPORT_STUDENTS,
			self::APPROVE_REQUESTS,
			self::MANAGE_ANNOUNCE,
			self::VIEW_REPORTS,
			self::ISSUE_CERTIFICATES,
			self::MANAGE_COMMERCE,
			self::MANAGE_PRICES,
			self::ACCESS_CAMPUS,
		);
	}

	/**
	 * Every capability the plugin knows about.
	 *
	 * @return array<int, string>
	 */
	public static function all(): array {
		return array_values(
			array_unique(
				array_merge(
					array_values( self::course_capabilities() ),
					self::plugin_capabilities()
				)
			)
		);
	}

	/**
	 * Capabilities granted to the LMS administrator role.
	 *
	 * @return array<int, string>
	 */
	public static function administrator_capabilities(): array {
		return array_merge( array( 'read', 'upload_files' ), self::all() );
	}

	/**
	 * Capabilities granted to the instructor role.
	 *
	 * Instructors manage their own courses and the students inside them, but
	 * they never touch pricing, commerce or global settings.
	 *
	 * @return array<int, string>
	 */
	public static function instructor_capabilities(): array {
		$course = self::course_capabilities();

		return array(
			'read',
			'upload_files',
			$course['edit_post'],
			$course['read_post'],
			$course['delete_post'],
			$course['edit_posts'],
			$course['publish_posts'],
			$course['edit_published_posts'],
			$course['delete_posts'],
			self::MANAGE_EDITIONS,
			self::MANAGE_CURRICULUM,
			self::MANAGE_MATERIALS,
			self::MANAGE_LIVE_CLASS,
			self::VIEW_STUDENTS,
			self::ENROLL_STUDENTS,
			self::APPROVE_REQUESTS,
			self::MANAGE_ANNOUNCE,
			self::VIEW_REPORTS,
			self::ACCESS_CAMPUS,
		);
	}

	/**
	 * Capabilities granted to the student role.
	 *
	 * @return array<int, string>
	 */
	public static function student_capabilities(): array {
		return array( 'read', self::ACCESS_CAMPUS );
	}
}
